config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
                        registrations: 'users/registrations',
                        omniauth_callbacks: "users/omniauth_callbacks"
                     }, 
                     path_names: { 
                        sessions: "sessions", 
                        sign_up: 'register', 
                        sign_in: 'login', 
                        sign_out: 'logout'
                     }

  root "home#index" 
  resources :home , only: [:index] do
    collection do 
      get :verification
    end
  end
  get ':user_name', to: "home#logged_in", as: "logged_in"
  resources :sshkeys, only:[:new, :create, :destroy]

  scope '/:user_name' do
    resources :relationships, only: [:index, :create, :destroy]
    get "relationships/followers", to: "relationships#followers", as: "followers"
    resources :likes, only: [:index]
    get "repository/:id/branches", to: "repositories#branches", as: "branches"
    post "repository/:id/branches/delete", to: "repositories#branch_delete", as: "branch_delete"
    get "repository/:id/commits", to: "repositories#commits", as: "commits"
    post "repository/:id/checkout", to: "repositories#checkout", as: "checkout"
    get "repository/:id/commit/diff", to: "repositories#commit_diff", as: "commit_diff"
    resources :repositories do
      resources :likes, only: [:create, :destroy]
      resources :pull_requests do
        member do
          get "commits", to: "pull_requests#commits", as: "commits"
          get "files_changed", to: "pull_requests#files_changed", as: "files_changed"
        end
        resources :comments, only:[:create, :update, :destroy]
        collection do
          get :compare
          get :diff
          get :close_index
        end
        member do
          post :merge
          post :close
          post :reopen
        end
      end
      resources :issues do
        resources :comments, only:[:create, :update, :destroy]
        member do
          get :toggle_status      
        end
      end
    end
  end
  get "/:user_name/repositories/:id/worktree/master/*file", to: "repositories#show" 

end

app/models/repository.rb
class Repository < ApplicationRecord
  blacklists = ["edit", "login", "logout", "password", "new", "cancel", "register", "confirmation", "repositories", "issues", "rails"]
  extend FriendlyId
  validates :title, presence: true, uniqueness: { scope: :user,
                                                  message: ": This title already exitsts!" },
                    format: { with: /\A[a-zA-Z0-9_]+\z/, message: "only allows alphabets, numbers and underscore." },
                    exclusion: { in: blacklists, message: ": Please change another repository title."},
                    length: {maximum: 64}
  belongs_to :user
  has_many :issues, dependent: :destroy
  has_many :pull_requests, dependent: :destroy
  has_many :likes
  has_many :users, through: :likes

  friendly_id :title, use: :slugged
  before_save :convert_slug_to_same_title

  def should_generate_new_friendly_id?
    slug.blank? || title_changed?
  end

  private
  def convert_slug_to_same_title
    self.slug = title 
  end
end

app/controllers/repositories_controller.rb
class RepositoriesController < ApplicationController
  before_action :set_repository, only: [:show, :edit, :update, :destroy, :branch_delete, :branches]
  before_action :set_request_format, only: [:show]
  before_action :set_git_remote_path, only: [:commits, :branches, :contributors, :branch_delete, :edit, :commit_diff]
  before_action :set_repo_file_path, only: [:branch_delete]

  def index
    return redirect_to new_user_session_path if current_user.blank?

    @user = find_user
    @repositories = repositories_order
    @repositories = @repositories.where(is_public: true) if current_user != find_user
    @repositories = @repositories.where('title LIKE ?', "%#{params[:search]}%") if params[:search].present?

    respond_to do |format|
      format.html { render :index }
    end
  end

  def show
    set_repo_file_path

    # synchronize git working repo 
    logger.info `git -C #{@base_path}#{@current_repo_path} fetch`
    logger.info `git -C #{@base_path}#{@current_repo_path} reset --hard origin/master`
    @contributors = []

    if Dir.entries("#{@base_path}#{@current_repo_path}") == [".", "..", ".git"]
      @is_new_repo = true 
      @branches = []
      @commits = 0
      @pull_request_able = []
    else
      @is_new_repo = false
      git_file = Git.open("#{@base_path}#{@current_repo_path}")
      logger.info `git -C #{@base_path}#{@current_repo_path} fetch`
      logger.info `git -C #{@base_path}#{@current_repo_path} reset --hard origin/#{git_file.current_branch}`
      @default_branch = @repository.default_branch
      @current_branch = git_file.current_branch
      @branches = git_file.branches.remote
      @commits = git_file.log(99999).count
      @contributors = git_file.log(99999).map{|commit| commit.committer.name}.uniq.select{|con| con != "GitHub"}
      @pull_request_able = @branches.map{|b| b.name }.select{|b| `git -C #{@base_path}#{@current_repo_path}.git diff #{@default_branch}...#{b}`.present? && current_repository.pull_requests.find_by(compare_branch: b).nil?}

      if request.fullpath.split("/").length == 4 # 專案根目錄的路徑 split 後只會有四個字串，超過四個字的都是比較下層的路徑
        @lines = []
        @readme = File.exist?("#{@base_path}#{@current_repo_path}/README.md")
        if @readme
          File.readlines("#{@base_path}#{@current_repo_path}/README.md").each do |line|
            @lines << line
          end
        end
        @lines = @lines.join("\n")
      end

      repo = Rugged::Repository.new("#{@base_path}#{@current_repo_path}")
      project = Linguist::Repository.new(repo, repo.head.target_id)
      @languages = project.languages.map{|lang| [lang[0], (lang[1].to_f / project.size * 100).round(2)]}
    end

    # get folder path from url
    path = request.original_fullpath
    if path.match(/\/repositories\/.+\/worktree\/master\/(.+)/)
      path = "#{@base_path}#{@current_repo_path}"+"/"+path.match(/\/repositories\/.+\/worktree\/master\/(.+)/)[1]
    else
      path = "#{@base_path}#{@current_repo_path}/."
    end

    files = []
    dirs = []

    is_file = File.file?(path)
    
    if @is_new_repo && current_user == find_user
      render :how_to_push
    elsif @is_new_repo && current_user != find_user
      render :empty_repo
    elsif is_file
      file_data = File.read(path)
      render :file , locals: {file_data: file_data}
    else
      Dir.entries(path).each do |file|

        last_commit = `git -C #{@base_path}#{@current_repo_path} log -1 --pretty=format:"%s___FengChenShowGit___%cr" #{path}/#{file}`
        commit_array = last_commit.split("___FengChenShowGit___")
        last_commit_message = commit_array[0]
        last_commit_time = commit_array[1]

        if [".", "..", ".git"].include?"#{file}"
        #rule out ".", "..", ".git"
        elsif File.file?(path+"/"+file)
          files << ["#{path.match(/^#{@base_path}#{@current_repo_path}\/(.+)/)[1]}/#{file}", last_commit_message, last_commit_time]
        else
          dirs << ["#{path.match(/^#{@base_path}#{@current_repo_path}\/(.+)/)[1]}/#{file}", last_commit_message, last_commit_time]
        end
      end
      render :dir, locals: {dirs: dirs, files: files, repository: @repository}
    end
  end

  def new
    @repository = Repository.new
  end

  def edit
    redirect_to repository_path if current_user != find_user
    @branches = @git_file.branches.remote
  end

  def create
    @repository = current_user.repositories.new(repository_params)
    @repository.errors.add(:is_public, "must select one") if params[:is_public].nil?

    if @repository.errors.any?
      render :new
    else
      @repository.is_public = params[:is_public]
      if @repository.save
        session[:repository_title] = @repository.title
        set_repo_file_path
        @repository.path = "#{@base_path}#{@current_repo_path}"

        full_dir = "#{@base_path}#{@current_repo_path}.git"
        working_dir = "#{@base_path}#{@current_repo_path}"

        # 新增一個空的資料夾
        `mkdir -p #{full_dir}`
        # 在剛剛新增的空資料夾中建立一個 bare repo
        #bare repo 可以被push clone
        #bare repo 中是沒有檔案的
        `git --bare init #{full_dir}`
        # 要讓網頁可以使用檔案、可以 commit 、需要的是 working repo （也就是我們平常 git init 之後的創造出來的 git 目錄）
        # 從 bare repo 中 clone 出一個 working repo，讓我們有檔案可以處理
        `git clone #{full_dir}  #{working_dir}`
        redirect_to repository_path(user_name: find_user.name, id: @repository.title), notice: 'You have created a repository.' 
      else
        render :new
      end
    end
  end

  def update
    old_repo_name = current_repository.title

    if @repository.update(repository_params)
      if params[:repository][:is_public] == "Public"
        @repository.is_public = true
      else
        @repository.is_public = false
      end
      @repository.save
      #update repo name in gitServer
      if old_repo_name != @repository.title
        set_repo_file_path
        logger.info `mv #{@base_path}/#{find_user.name}/#{old_repo_name}.git #{@base_path}/#{find_user.name}/#{@repository.title}.git`
        logger.info `mv #{@base_path}/#{find_user.name}/#{old_repo_name} #{@base_path}/#{find_user.name}/#{@repository.title}`
        logger.info `git -C #{@base_path}/#{find_user.name}/#{@repository.title} remote set-url origin #{ENV["GIT_PUSH_INSTRUCT"]}/#{find_user.name}/#{@repository.title}.git`
      end
      redirect_to repository_path(user_name: find_user.name, id: @repository.title), notice: 'This repository has updated.'
    else
      render :edit
    end
  end

  def destroy
    #destroy whole repo folder on git server
    set_repo_file_path
    `rm -rf #{@base_path}#{@current_repo_path}.git`
    `rm -rf #{@base_path}#{@current_repo_path}`

    @repository.destroy
    redirect_to repositories_path, notice: 'This repository is deleted！'
  end

  def checkout
    set_repo_file_path
    `git -C #{@base_path}#{@current_repo_path} checkout #{params[:branch]}`
    redirect_to repository_path(user_name: find_user.name, id: current_repository.title )
  end

  def commits
    @commits = @git_file.log(99999)
    @branches = @git_file.branches.remote.map{|b| b.name}
    @contributors = @git_file.log(99999).map{|c| c.committer.name}.uniq.select{|n|n != "Github"}.count
  end

  def commit_diff
    @commit_diff_files = diff_files_in_commit(params[:sha])

    @branches = @git_file.branches.remote
    @commits = @git_file.log(99999).count
    @contributors = @git_file.log(99999).map{|c| c.committer.name}.uniq.select{|n|n != "Github"}.count
  end

  def branches
    @branches = @git_file.branches.remote
    @commits = @git_file.log(99999).count
    @contributors = @git_file.log(99999).map{|c| c.committer.name}.uniq.select{|n|n != "Github"}.count
  end

  def branch_delete
    if params[:branch] != @repository.default_branch
      `git -C #{@base_path}#{@current_repo_path} branch -D #{params[:branch]}`
      `git -C #{@base_path}#{@current_repo_path}.git branch -D #{params[:branch]}`
      `git -C #{@base_path}#{@current_repo_path} fetch --all -p`
      flash[:notice] = "Branch deleted successfully!"
    else
      flash[:notice] = "You can't delete default branch!"
    end
    redirect_to repository_path(user_name: find_user.name, id: current_repository.title)
  end

  private
  def set_repository
    @repository = find_user.repositories.friendly.find(params[:id])
    session[:repository_title] = @repository.title
  end

  def repository_params
    params.require(:repository).permit(:title, :description, :is_public, :default_branch)
  end

  def set_request_format
    request.format = :html
  end

  def diff_files_in_commit(commit)
    diff_commit = DiffPullRequest.new(
      "#{@base_path}#{@current_repo_path}",
      sha: commit
    )
    diff_commit.diff_in_files
  end
end

app/views/repositories/_README.html.erb
<div class="dir-container" >
  <table class="table">
		<thead class="thead-light">
			<tr>
				<th>
					<i class="far fa-file-alt" style="color: rgba(255,255,255,.5)"></i> Readme
				</th>
			</tr>
		</thead>
		<tbody>
			<tr>
				<td class="readme" style="color: #ffffff;">
					<%= to_markdown(file_datas)%>
				</td>
			</tr>
		</tbody>
  </table>
</div>

app/views/repositories/_file.html.erb
<!-- _file.html.erb -->

<div class="dir-container">
  <table class="table">
	  <thead class="thead-light">
		  <tr>
			  <th>
				  Files
			  </th>
		  </tr>
		  <tr>
			  <td>
				<%= markdown("```\n"+@file_data+"```\n") %>
			  </td>
		  </tr>
	  </thead>
  </table>
</div>

app/views/repositories/_how_to_push.html.erb
<!-- _how_to_push.html.erb -->

<div class="push-instruction-container my-5">
  <div class="box-header">
  	<h3>Instructions</h3>
  </div>
  <div class="box-row">
  	<h3>
  		Push an existing repository from the command line
  	</h3>
  	<%= markdown("```\ngit remote add origin #{ENV["GIT_PUSH_INSTRUCT"]+@current_repo_path+".git"}
git push -u origin master\n ```") %>
  </div>
</div>

app/views/repositories/_show.html.erb
<div class="this-is-share-repo-navebar public"> 
  <div>
    <%= render "shared/repo_navbar"%>
  </div>

  <div class="container">

    <% if @is_new_repo %>
    <% else %>
      <div class="git-feature-bar col-12">
        <ul class="nav">
          <%= link_to branches_path(user_name: find_user.name, id: @repository.title), class: "nav-link mx-auto" do %>
            <i class="fas fa-code-branch"></i> <span> Branches </span> <%= @branches.count %>
          <% end %>
          <%= link_to commits_path(user_name: find_user.name, id: @repository.title), class: "nav-link mx-auto" do %>
            <i class="fas fa-dot-circle"></i> <span> Commits </span> <%= @commits %>
          <% end %>
          <div class="nav-link mx-auto">
            <i class="fas fa-user-friends"></i> <span> Contributors </span> <%= @contributors.count %>
          </div>
        </ul>
      </div>
      <div class="col-12 d-flex m-3 percentage-bar">
        <% @languages.each do |lang|%>
          <div class="m-auto">
            <%= lang[0] %>
            <%= lang[1] %> % 
          </div>
        <% end %>
      </div>
    <% end %>
      
      <div class="current-branch">
          <i class="fas fa-code-branch"></i> Current Branch : <%= @current_branch %>
      </div>
      <% @pull_request_able.each do |branch| %>
        <% if find_user == current_user%>
          <div class="w-100 other-branch">Create a pull request <%= link_to "#{branch}", new_repository_pull_request_path(repository_id: current_repository.title ,compare_branch: branch, base_branch: current_repository.default_branch) %> ? </div>
        <% end %>
      <% end %>
      
      <div class="show-content col-8">
      
      </div>
      <div class="btn-copy file-btn">

          <button class="btn code-file-btn" type="button" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
            Clone or download
          </button>

        <div class="collapse down" id="collapseExample">
          <div class="card card-body col-8">
            <h3>Clone with SSH</h3> 
            <p>Use a password protected SSH key.</p>
            <div class="row">
              <div class="collapse-title col-8">
                <input id="copyLink" class="copyLink col-12" value= "<%= ENV["GIT_PUSH_INSTRUCT"] %>/<%= @repository.user.name %>/<%= @repository.title %>.git" readonly="readonly">
              </div>
              <div class="collapse-btn col-3">
                <button class="btn code-file-btn" type="button"data-clipboard-target="#copyLink">Copy</button>
              </div>
            </div>
          </div>
        </div>
      </div>
  </div>
</div>

app/views/repositories/branches.html.erb
<div class="your-branches public"> 
  <%= render "shared/repo_navbar"%>
  <div class="git-feature-bar col-12">
    <ul class="nav">
      <%= link_to branches_path(user_name: find_user.name, id: @repository.title), class: "nav-link mx-auto" do %>
        <i class="fas fa-code-branch"></i> <span> Branches </span> <%= @branches.count %>
      <% end %>
      <%= link_to commits_path(user_name: find_user.name, id: @repository.title), class: "nav-link mx-auto" do %>
        <i class="fas fa-dot-circle"></i> <span> Commits </span> <%= @commits %>
      <% end %>
      <div class="nav-link mx-auto">
        <i class="fas fa-user-friends"></i> <span> Contributors </span> <%= @contributors %>
      </div>
    </ul>
  </div>

  <table class="table">
    <thead>
      <th class="gray">Your branches</th>
      <td class="gray"></td>
      <td class="gray"></td>
    </thead>
    <tbody>
      <% @branches.sort_by{|b| b.gcommit.date}.reverse.each do |branch| %>
        <tr>
          <th class="row pd">
            <%= link_to "#{branch.name}", checkout_path(user_name: find_user.name, id: current_repository.title, branch: branch.name), method: "POST"%>
          </th>
          <td class="pd">Update <%= time_ago_in_words(branch.gcommit.date) %> by <%= branch.gcommit.author.name %></td>
          <td class="pd">
            <%= link_to branch_delete_path(user_name: find_user.name, id: current_repository.title, branch: branch.name), method: "POST" do %>
              <i class="fas fa-trash icon"></i>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/repositories/commit_diff.html.erb
<div class="this-is-share-repo-navebar public">
  <%= render "shared/repo_navbar"%>
  <div class="git-feature-bar col-12">
    <ul class="nav">
      <%= link_to branches_path(user_name: find_user.name, id: current_repository.title), class: "nav-link mx-auto" do %>
        <i class="fas fa-code-branch"></i> <span> Branches </span> <%= @branches.count %>
      <% end %>
      <%= link_to commits_path(user_name: find_user.name, id: current_repository.title), class: "nav-link mx-auto" do %>
        <i class="fas fa-dot-circle"></i> <span> Commits </span> <%= @commits %>
      <% end %>
      <div class="nav-link mx-auto">
        <i class="fas fa-user-friends"></i> <span> Contributors </span> <%= @contributors %>
      </div>
    </ul>
  </div>

  <div>
    <h3 class="commit-diff-title m-4">File changes</h3>
    <%= render "pull_requests/diff_content", diff: @commit_diff_files %>
  </div>
  
</div>

app/views/repositories/commits.html.erb
<div class="this-is-share-repo-navebar public">
  <%= render "shared/repo_navbar"%>
  <div class="commits-container">

    <div class="git-feature-bar col-12">
      <ul class="nav">
        <%= link_to branches_path(user_name: find_user.name, id: current_repository.title), class: "nav-link mx-auto" do %>
          <i class="fas fa-code-branch"></i> <span> Branches </span> <%= @branches.count %>
        <% end %>
        <%= link_to commits_path(user_name: find_user.name, id: current_repository.title), class: "nav-link mx-auto" do %>
          <i class="fas fa-dot-circle"></i> <span> Commits </span> <%= @commits.count %>
        <% end %>
        <div class="nav-link mx-auto">
          <i class="fas fa-user-friends"></i> <span> Contributors </span> <%= @contributors %>
        </div>
      </ul>
    </div>
    <div class="commits-max-w">
      <h3 class="my-5">
        Commits
      </h3>
      <% @commits.each do |commit| %>
        <div class="commit-info-container row my-3 p-2">
          <div class="commit-info-wrap row col-8">
            <p class="commit-message col-12 m-0">
              <%= commit.message %>
            </p>
            <div class="col-12">
              <%= commit.author.name %> commit <%= time_ago_in_words(commit.date.utc) %> ago
            </div>
          </div>
          <div class="commit-sha col-4">
            <%= link_to "View change", commit_diff_path(user_name: find_user.name,id: current_repository.title, sha: commit.sha) %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/repositories/contributors.html.erb
<%= @contributors %>

app/views/repositories/dir.html.erb
<!-- dir.html.erb -->
<%= render "show"%>
<div class="dir-container">
  <table class="table">

		<thead class="thead-light">
			<tr>
				<th>
					Folders
				</th>
			</tr>
		</thead>

		<% dirs.each do |dir| %>
			<tr>
				<td class="d-flex">
					<div class="col-3">
						<i class="fas fa-folder" style="color: rgba(255,255,255,.5)"></i>
						<a href="/<%= repository.user.name %>/repositories/<%= repository.title %>/worktree/master/<%= dir[0] %>" style="color: rgba(255,255,255,1)"> <%= dir[0].match(/^.+\/(.+)$/)[1] %> </a>
					</div>
					<div class="col-7" style="color: rgba(255,255,255,.5)">
						<%= dir[1]%>
					</div>
					<div class="col-2" style="color: rgba(255,255,255,.5)">
						<%= dir[2]%>
					</div>
				</td>
			</tr>
		<% end %>

		<% files.each do |file| %>
			<tr>
				<td class="d-flex">
					<div class="col-3">
						<i class="far fa-file-alt" style="color: rgba(255,255,255,.5)"></i>
						<a href="/<%= repository.user.name %>/repositories/<%= repository.title %>/worktree/master/<%= file[0] %>" style="color: rgba(255,255,255,1)"> <%= file[0].match(/^.+\/(.+)$/)[1] %> </a>
					</div>
					<div class="col-7" style="color: rgba(255,255,255,.5)">
						<%= file[1]%>
					</div>
					<div class="col-2" style="color: rgba(255,255,255,.5)">
						<%= file[2]%>
					</div>
				</td>
			</tr>
		<% end %>
  </table>

	<% if @readme.present? %>
		<%= render partial: 'README', locals: {file_datas: @lines} %>
	<% end %>

</div>


app/views/repositories/edit.html.erb
<div class="projet-setting">
  <div>
    <%= render "shared/repo_navbar"%>
  </div>
  <div class="repoedit-container my-5">
    <div class="col-12">
      <h2 class="mt-5">Settings</h2>
      <div class="title-bottom-line"></div>
      <%= form_with(model: @repository, url: repository_path(user_name: find_user.name, id: current_repository.title), local: true, method: :put) do |form| %>
        <% if @repository.errors.any? %>
          <h2>There is something wrong!</h2>
          <% @repository.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        <% end %>

        <div class="field row m-auto py-3">
          <%= form.label :title , "Repository title", class: "col-4 settings-title" %>
          <%= form.text_field :title, class: "form-control col-7"%>
        </div>

        <div class="field row m-auto py-3">
          <%= form.label :description, "Repository description", class: "col-4 settings-title"  %>
          <%= form.text_field :description, class: "form-control col-7"%>
        </div>

        <div class="field row m-auto py-3 settings-title sele-branch">
          <%= form.label :default_branch, "Repository default branch"%>
          <%= select("repository", "default_branch", @branches.collect {|b| b.name }, class: "drop-down")%>
        </div>

        <div class="field row m-auto py-3 settings-title sele-branch">
          <%= form.label :is_public, "Repository privacy option"%>
          <%= select("repository", "is_public", ["Public", "Private"], class: "drop-down")%>
        </div>

        <div class="actions">
          <%= form.submit "Update repository", class: "btn mx-3"%>
        </div>
        <div class="col-12 bottom-line"></div>
      <% end %>
            
      <h2 class="mt-5">Delete repository</h2>
      <div class="title-bottom-line"></div>
      <p class="my-3">Once you delete a repository, there is no going back. Please be certain.</p>
      <%= button_to "Delete this repository", repository_path, data: { confirm: "Are you sure?" }, method: :delete, class: "btn btn-danger my-2 mx-1"%>
    </div>
  </div>
</div>

app/views/repositories/how_to_push.html.erb
<!-- how_to_push.html.erb -->
<div class="instructions">

		<%= render "show"%>
		
		<div class="push-instruction-container">
		  <div class="box-header">
		  	<h3>Instructions</h3>
		  </div>
		  <div class="box-row">
		  	<h4>
		  	  Push an existing repository from the command line. Please make sure you add your SSH key.
		  	</h4>
			  	<%= markdown("```\ngit remote add origin #{ENV["GIT_PUSH_INSTRUCT"]+@current_repo_path+".git"}\ngit push -u origin master\n ``````") %>
		  </div>
		</div>

</div>

app/views/repositories/index.html.erb
<div class="logged-in-my-repo public">


      <div class="container my-5">
        <div class="row">
          <div class="user-info-container col-12 col-md-3">
            <div class="avatar-wrap">
              <% if find_user.image? %>
                  <%= image_tag(find_user.image_url) %>
              <% else %>
                  <img src="https://images.plurk.com/43tXxZ1MP3bwW7lyZbunAy.png">
              <% end %>
            </div>
            <h4 class="my-2 user-name"><%= find_user.name %></h4>
          </div>
          <div class="repositories-container col-12 col-md-9 row p-3">
            <div class="repositories-title col-12">
              <ul class="nav">
                <li class="nav-item mx-3">
                  <%= link_to "Overview", logged_in_path(user_name: find_user.name), class: "nav-link"%>
                </li>
                <li class="nav-item mx-3">
                  <%= link_to "Repositories #{find_user.repositories.count}", repositories_path, class: "nav-link the-bottom" %>
                </li>
                <li class="nav-item mx-3">
                  <%= link_to "Following #{find_user.following_users.count}", relationships_path(user_name: find_user.name), class: "nav-link" %>
                </li>
                <li class="nav-item mx-3">
                  <%= link_to "Followers #{find_user.followers.count}", followers_path(user_name: find_user.name), class: "nav-link" %>
                <li class="nav-item mx-3">
                  <%= link_to "Stars #{find_user.liked_repositories.count}", likes_path(user_name: find_user.name), class: "nav-link" %>
                </li>
              </ul>
              <div class="line">
                <div class="title-bottom-line"></div>
              </div>
            </div>

            <form class="form-inline my-3 lg-0 col-12 repo-search">
              <%= form_tag repositories_path, method: :get do %>
              <%= text_field_tag :search, params[:search], placeholder: "Search..." , class:"repo-search col-10" %>
              <button class="btn btn-outline my-2 my-sm-0 ml-5 repo-btn" type="submit"><i class="fas fa-search"></i></button>
              <% end %>
            </form>

            <% @repositories.each do |repo|%>
              <div class="p-3 col-12">
                <div class="repositories-repository-wrap p-5 row project-block">
                  <div class="col-10">
                    
                    <h4>
                      <%= link_to "#{repo.title}", repository_path(id: repo)%>
                    </h4>
                    <div>
                      Create <%= time_ago_in_words(repo.created_at) %> ago
                    </div>
                  </div>

                  <% if current_user.liked_repositories.find_by(id: repo.id).nil? %>
                    <%= link_to repository_likes_path(repository_id: repo), class: "star-container", method: "POST" do %>
                      <div class="star">
                        <i class="far fa-star"></i><span> <%= repo.likes.count %> </span>
                      </div>
                    <% end %>
                  <% else %>
                    <%= link_to repository_like_path(repository_id: repo, id: current_user.liked_repositories.find_by(id: repo.id), repo_id: repo.id), class: " star-container", method: "DELETE" do %>
                      <div class="star">                      
                        <i class="fas fa-star"></i><span>  <%= repo.likes.count %> </span>
                      </div>
                    <% end %>
                  <% end %>

                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>


</div>

app/views/repositories/show.html.erb
<div>
  <%= render "shared/repo_navbar"%>
</div>
</br>
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @repository.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @repository.description %>
</p>

<p>
  <strong>User:</strong>
  <%= @repository.user.name %>
</p>

<%= link_to 'Back', repositories_path %>

<% if  @is_file %>
  <%= render "file" %>
<% elsif @dirs == [] && @files == [] %>
  <%= render "how_to_push" %>
<% else %>
  <%= render "dir" %>
<% end %>