config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
                        registrations: 'users/registrations',
                        omniauth_callbacks: "users/omniauth_callbacks"
                     }, 
                     path_names: { 
                        sessions: "sessions", 
                        sign_up: 'register', 
                        sign_in: 'login', 
                        sign_out: 'logout'
                     }

  root "home#index" 
  resources :home , only: [:index] do
    collection do 
      get :verification
    end
  end
  get ':user_name', to: "home#logged_in", as: "logged_in"
  resources :sshkeys, only:[:new, :create, :destroy]

  scope '/:user_name' do
    resources :relationships, only: [:index, :create, :destroy]
    get "relationships/followers", to: "relationships#followers", as: "followers"
    resources :likes, only: [:index]
    get "repository/:id/branches", to: "repositories#branches", as: "branches"
    post "repository/:id/branches/delete", to: "repositories#branch_delete", as: "branch_delete"
    get "repository/:id/commits", to: "repositories#commits", as: "commits"
    post "repository/:id/checkout", to: "repositories#checkout", as: "checkout"
    get "repository/:id/commit/diff", to: "repositories#commit_diff", as: "commit_diff"
    resources :repositories do
      resources :likes, only: [:create, :destroy]
      resources :pull_requests do
        member do
          get "commits", to: "pull_requests#commits", as: "commits"
          get "files_changed", to: "pull_requests#files_changed", as: "files_changed"
        end
        resources :comments, only:[:create, :update, :destroy]
        collection do
          get :compare
          get :diff
          get :close_index
        end
        member do
          post :merge
          post :close
          post :reopen
        end
      end
      resources :issues do
        resources :comments, only:[:create, :update, :destroy]
        member do
          get :toggle_status      
        end
      end
    end
  end
  get "/:user_name/repositories/:id/worktree/master/*file", to: "repositories#show" 

end

app/models/pull_request.rb
class PullRequest < ApplicationRecord
  belongs_to :repository
  belongs_to :user
  validates :name, presence: true,
                   length: {maximum: 100}
  has_many :comments, dependent: :destroy, as: :commentable
end

app/controllers/pull_requests_controller.rb
class PullRequestsController < ApplicationController
  before_action :set_pull_request, only: [:show, :edit, :update, :commits, :files_changed, :merge, :close, :reopen]
  before_action :set_git_remote_path, only: [:new, :show, :create, :index, :commits, :compare, :diff, :files_changed, :merge]

  def index
    @pull_requests = current_repository.pull_requests.order("id DESC").page(params[:page]).per(5)
    @pull_request_able = @git_file.branches.remote.map{|b| b.name }.select{|b| `git -C #{@base_path}#{@current_repo_path}.git diff #{@default_branch}...#{b}`.present? && current_repository.pull_requests.find_by(compare_branch: b).nil?}
  end

  def close_index
    @pull_requests = current_repository.pull_requests.order("id DESC").page(params[:page]).per(5)
  end

  def compare
    @pull_request = PullRequest.new
    @branches = @git_file.branches.remote
  end

  def diff
    @base_branch = params[:pull_request][:base_branch]
    @compare_branch = params[:pull_request][:compare_branch]
    @diff_files = diff_in_files(@base_branch, @compare_branch)

    ok, msg = check_pull_request_available(@base_branch, @compare_branch)
    if ok
    else
      redirect_to compare_repository_pull_requests_path(user_name: find_user.name), notice: msg
    end
  end

  def new
    @branches = @git_file.branches.remote
    @pull_request = current_repository.pull_requests.new
    @pull_request.name = params[:compare_branch]
    @commits = `git -C #{@base_path}#{@current_repo_path}.git log #{params[:base_branch]}..#{params[:compare_branch]}`.scan(/\w+/).select{|word| word.length == 40}.map{ |sha| @git_file.gcommit(sha)}

    @base_branch = params[:base_branch] 
    @compare_branch = params[:compare_branch]
    @pull_request.diff = diff_in_files(@base_branch, @compare_branch)
  end

  def create
    @pull_request = find_user.repositories.find_by(slug: params[:repository_id]).pull_requests.build(pull_request_params)
    @pull_request.user = current_user
    @pull_request.repository_pull_request_index = current_repository.pull_requests.count + 1
    @pull_request.compare_branch = params[:compare_branch]
    @pull_request.base_branch = params[:base_branch]
    @pull_request.diff = diff_in_files(@pull_request.base_branch, @pull_request.compare_branch)

    if @pull_request.save 
      redirect_to repository_pull_requests_path(user_name: current_user.name), notice: 'You have created a pull request！' 
    else
      render :new
    end
  end

  def show
    `git -C #{@base_path}#{@current_repo_path} pull`
    if @pull_request.commits.present?
      @commits = @pull_request.commits.map{ |sha| @git_file.gcommit(sha)}
    else
      @commits_sha = `git -C #{@base_path}#{@current_repo_path}.git log #{@pull_request.base_branch}..#{@pull_request.compare_branch}`.scan(/\w+/).select{|word| word.length == 40}
      @commits = @commits_sha.map{ |sha| @git_file.gcommit(sha)}
    end

    @comments = @pull_request.comments
    @comment = Comment.new
    @pull_request.commits = @commits_sha

    `git -C #{@base_path}#{@current_repo_path} checkout #{@pull_request.compare_branch}`
    @have_conflicts = `git -C #{@base_path}#{@current_repo_path} merge --no-commit --no-ff #{@pull_request.base_branch}`.scan(/Automatic merge failed; fix conflicts and then commit the result./).present?
    `git -C #{@base_path}#{@current_repo_path} merge --abort`
    `git -C #{@base_path}#{@current_repo_path} checkout #{@pull_request.base_branch}`
  end

  def edit
  end

  def update
    @pull_request.update(pull_request_params)
  end

  def commits
    if @pull_request.commits.present?
      @commits = @pull_request.commits.map{ |sha| @git_file.gcommit(sha)}
    else
      @commits_sha = `git -C #{@base_path}#{@current_repo_path}.git log #{@pull_request.base_branch}..#{@pull_request.compare_branch}`.scan(/\w+/).select{|word| word.length == 40}
      @commits = @commits_sha.map{ |sha| @git_file.gcommit(sha)}
    end
  end

  def merge
    if find_user == current_user
      `git -C #{@base_path}#{@current_repo_path} pull origin #{@pull_request.compare_branch}`
      @pull_request.commits = `git -C #{@base_path}#{@current_repo_path}.git log #{@pull_request.base_branch}..#{@pull_request.compare_branch}`.scan(/\w+/).select{|word| word.length == 40}
      `git -C #{@base_path}#{@current_repo_path} checkout #{@pull_request.base_branch}`
      `git -C #{@base_path}#{@current_repo_path} merge #{@pull_request.compare_branch}`
      @pull_request.status = "Merged"
      @pull_request.save
      `git -C #{@base_path}#{@current_repo_path} push origin #{@pull_request.base_branch}`
      flash[:notice] = "This pull request has been merged."
    else
      flash[:notice] = "Only owner can merge pull requests"
    end
    redirect_to repository_pull_request_path(user_name: find_user.name, repository_id: current_repository.title, id: @pull_request)
  end

  def close
    if find_user == current_user
      @pull_request.status = 'Close'
      @pull_request.save
      flash[:notice] = "This pull request has been closed."
    else
      flash[:notice] = "Only owner can close pull requests"
    end
      redirect_to repository_pull_request_path(user_name: find_user.name, repository_id: current_repository.title, id: @pull_request)
  end

  def reopen
    if find_user == current_user
      @pull_request.status = 'Open'
      @pull_request.save
      flash[:notice] = "This pull request has been opened."
    else
      flash[:notice] = "Only owner can reopen pull requests"
    end
    redirect_to repository_pull_request_path(user_name: find_user.name, repository_id: current_repository.title, id: @pull_request)
  end

  def files_changed
    if diff_in_files(@pull_request.base_branch, @pull_request.compare_branch) != []
      @pull_request.update_columns(diff: diff_in_files(@pull_request.base_branch, @pull_request.compare_branch))
    end
    @pull_request.diff
  end

  private
  def pull_request_params
    params.require(:pull_request).permit(:name, :description)
  end

  def set_pull_request
    @pull_request = PullRequest.find(params[:id])
  end

  def check_pull_request_available(base_branch, compare_branch)
    msg = ""
    if diff_in_files(base_branch, compare_branch).present?
      if PullRequest.where("base_branch = ? AND compare_branch = ? AND status = ?", base_branch, compare_branch, "Open" ).present?
        msg = "These two branches has already created a pull request, please choose other branches."
        return [false, msg]
      end 
      return [true,msg]
    else
      msg = "These two branches has no difference, please choose other branches."
      return [false, msg]
    end
  end

  def diff_in_files(base_branch, compare_branch)
    diff_pr = DiffPullRequest.new(
      "#{@base_path}#{@current_repo_path}.git",
      base_branch: base_branch,
      compare_branch: compare_branch
    )
    diff_pr.diff_in_files
  end
  
end

app/views/pull_requests/_diff_content.html.erb
<div class = "diff-content">
	<div class = "row">
    <div class = "col-11">
      <% diff.each do |diff_file| %>
        <div class="file-header">
          <div class = "file-title">
            <i class="far fa-file-alt"></i><%= "  #{diff_file["file_name"]}" %>
          </div>
        </div> 
        <div class="file-content">
          <% diff_file["code"].each do |block| %>
            <div class="block-index">
              <%= block[0] %>
            </div>
            <div class="block-content">
              <% block[1].each do |line| %>
                <div class="<%= line[0] %>">
                  <%= code(line[1], diff_file["file_name"]).html_safe %>
                </div>
              <% end %>
            </div>
          <% end %>
        </div>
      <br>
      <% end %>
    </div>
  </div>
</div>

app/views/pull_requests/close_index.html.erb
<div class="pull-request pull-request-close public">
  
    <div>
      <%= render "shared/repo_navbar"%>
    </div>

    <div class="row sele">
      <form class="form-inline my-2 my-lg-0 col-12 issue-show repo-search">
        <input
          class="form-control mr-sm-2 col-9 "
          type="search"
          placeholder="Search"
          aria-label="Search"
        />
      <div class="new-pr col-3">
        <%= link_to "New pull request", compare_repository_pull_requests_path , class: "btn col-12" %>
      </div>
      </form>
     
    </div>

    <div class=" my-5">
      <div class="issue-title row p-2 open">
        <div class="description-title col-4"><%= current_repository.pull_requests.where(status: ["Close", "Merged"]).count %> Records</div>
         <div class="status-title col-7"><i class="fas fa-lock-open"></i> <%= link_to "Open #{current_repository.pull_requests.where(status: "Open").count}", repository_pull_requests_path(user_name: find_user.name, id: current_repository.title) %>  |
          <i class="fas fa-lock"></i> 
        <%= link_to "Close #{current_repository.pull_requests.where(status: ["Close", "Merged"]).count}", close_index_repository_pull_requests_path(user_name: find_user.name, id: current_repository.title)%></div>
      </div>
      <% if @pull_requests.present? %>
        <% @pull_requests.where(status: ["Close", "Merged"]).each do |pull_request| %>
        <div class="container">
          <div class="row the-tr">
            <div class="col-4 mt-2"><%= pull_request.status%></div>
            <div class="col-7 row"> 
            <%= link_to pull_request.name,repository_pull_request_path(id: pull_request.id),class:"col-12" %>        
              <p class="col-12 ago">#<%= pull_request.repository_pull_request_index %> opened <%= time_ago_in_words(pull_request.created_at) %> ago </p>
            </div>
          </div>
        </div>
        <% end %>
      <% else %>
        <div class="text-center p-5">
          <h3>There aren't any open pull requests.</h3>
          <h4>Try to create new pull requests.</h4>
        </div>
      <% end %>
    </div>

  <nav aria-label="Page navigation example" class="pageA" >
    <ul class="pagination">
      <%= paginate @pull_requests, window: 2, class: "pagination-contant" %>
    </ul>
  </nav>

</div>

app/views/pull_requests/commits.html.erb
<%= render "shared/repo_navbar"%>
<%= render "shared/pull_request_bar"%>



<div class="timeline-group mt-5">
  <% @commits.each do |commit|%>
  <div class="timeline-container container">
    <div class="row">
      <div class="col-md-12">
        <ul class="timeline-history list-group list-group-flush">
          <li>
            <div class="row list-item title">
              <p><%= commit.committer.name %></p>
              <p><%= time_ago_in_words(commit.date.utc) %>ago</p>
            </div>
              <div class="row list-item number">
                <p class="p-message col-10"><%= commit.message %></p>
                <p class="p-commit col-2"><%= commit.sha[0..7] %></p>
            </div>
          </li>
        </ul>
      </div>
    </div>
  </div>


  <% end %>
</div>

app/views/pull_requests/compare.html.erb
<div class="compare_branch public">
  <div>
    <%= render "shared/repo_navbar"%>
  </div>

  <%= form_with(model: @pull_request,url: diff_repository_pull_requests_path, method: :get, local: true) do |form| %>
    <div class="field row m-auto py-3">
      <%= form.label :base_branch, "Base branch "%>
      <%= select("pull_request", "base_branch", @branches.collect {|b| b.name })%>
    </div>
    <div class="field row m-auto py-3">
      <%= form.label :compare_branch, "Compare branch "%>
      <%= select("pull_request", "compare_branch", @branches.collect {|b| b.name })%>
    </div>
    <div class="actions">
      <%= form.submit "New pull request", class: "btn mx-3"%>
    </div>
  <% end %>
</div>

app/views/pull_requests/diff.html.erb
<div class="diff">
  <div>
    <%= render "shared/repo_navbar"%>
  </div>
  <div>
  	<%= link_to "Create Pull Request", new_repository_pull_request_path(user_name: find_user.name, base_branch: @base_branch, compare_branch: @compare_branch), class: "btn reopen-btn" %>
  </div>
  <%= render "diff_content", diff: @diff_files %>
</div>

app/views/pull_requests/edit.html.erb
<div>
  <%= render "shared/repo_navbar"%>
</div>
<% if @pull_request.errors.any? %>
  <ul>
    <% @pull_request.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for([:repository, @pull_request]) do |form|%>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %> 

app/views/pull_requests/files_changed.html.erb
<%= render "shared/repo_navbar" %>
<%= render "shared/pull_request_bar" %>
<%= render "diff_content", diff: @pull_request.diff %>

app/views/pull_requests/index.html.erb
<div class="pull-request public">
  
    <div>
      <%= render "shared/repo_navbar"%>
    </div>

    <div class="row col-12 fome-inline my-2 my-lg-0 issue-show repo-search">
      <input
        class="form-control mr-sm-2 col-9"
        type="search"
        placeholder="Search"
        aria-label="Search"
      />
      </form>

      <div class="new-pr col-3">
        <%= link_to "New pull request", compare_repository_pull_requests_path , class: "btn col-12" %>
      </div>
    </div>

    <div class="my-5">
      <div class="issue-title row p-2 open">
        <div class="description-title col-4"><%= current_repository.pull_requests.where(status: "Open").count %> Records</div>
        <div class="status-title col-7">
           <i class="fas fa-lock-open"></i> 
           <%= link_to "Open #{current_repository.pull_requests.where(status: "Open").count}", repository_pull_requests_path(user_name: find_user.name, id: current_repository.title) %> 
            | 
           <i class="fas fa-lock"></i> 
           <%= link_to "Close #{current_repository.pull_requests.where(status: ["Close", "Merged"]).count}", close_index_repository_pull_requests_path(user_name: find_user.name, id: current_repository.title)%>
        </div>
      </div>
      <% if @pull_requests.present? %>
        <% @pull_requests.where(status: "Open").each do |pull_request| %>
        <div class="container">
          <div class="row the-tr">
            <div class="col-4 mt-2 content"><%= pull_request.status%></div>
            <div class="col-6 row"> 
            <%= link_to pull_request.name,repository_pull_request_path(id: pull_request.id),class: "col-12 issue-name" %>        
              <p class="col-12 ago">#<%= pull_request.repository_pull_request_index %> opened <%= time_ago_in_words(pull_request.created_at) %> ago </p>
            </div>
          </div>
        </div>
        <% end %>
      <% else %>
        <div class="text-center p-5">
          <h3>There aren't any open pull requests.</h3>
          <h4>Try to create new pull requests?</h4>
        </div>
      <% end %>
    </div>

  <nav aria-label="Page navigation example" class="pageA" >
    <ul class="pagination">
      <%= paginate @pull_requests, window: 2, class: "pagination-contant" %>
    </ul>
  </nav>

</div>

app/views/pull_requests/show.html.erb
<div>
  <%= render "shared/repo_navbar"%>
</div>



<div class="container">
  <div class="row">
    <div class="issue-title col-10 ">
      <div class="issue_name_inactive ">
        <h1><%= @pull_request.name %></h1>
      </div>
      <%= form_for([:repository, @pull_request],remote: true) do |form|%>
      <div class= "issue_name_active"><h4><%= form.text_field :name%></h4></div> 
    </div>   
    <div class ="issue_button col-2">
      <%= form.button "update", id: "issue_update", class: "btn btn-secondary", type: "submit"%>
      <button id = "issue_edit" class="issue_edit btn btn-secondary">Edit</button>   
      <% end %> 
    </div>
  </div>
</div>


<div class="second-container col-lg-10 col-md-10 col-sm-12 mt-3 mb-5"> 
  <div class="row">
    <div class="col-1">
      <% if @pull_request.status == "Open" %>
        <span class="reopen-btn"><%= @pull_request.status %></span>
      <% elsif @pull_request.status == "Merged"%>
        <span class="merged-btn"><%= @pull_request.status%></span>
      <% else %>
        <span class="close-btn"><%= @pull_request.status%></span>
      <% end %>
    </div>


    <div class="pr-message col-lg-10 col-sm-12">
      <p> <%= current_user.name %> want to merge <%= @commits.count %> commit into <%= link_to @pull_request.base_branch, checkout_path(find_user.name, id: current_repository.title, branch: @pull_request.base_branch)%> from <%= link_to @pull_request.compare_branch, checkout_path(find_user.name, id: current_repository.title, branch: @pull_request.compare_branch) %> <p>
    </div>
  </div>

  <%= render "shared/pull_request_bar"%>


  <div class="issue_description comment-info-container card">
    <div class="card-header issue-comment-name">
      <button type="button" class="btn btn-sm dropdown-toggle dropdown-toggle-split comment-more" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></button>   
      <div class ="issue_description_button dropdown-menu">
        <div id = "issue_description_edit" class="btn">Edit</div>  
      </div>
      <h4>Developer</h4>
      <div class="bottom-line"></div> 
    </div>
    <div class="card-body">
      <blockquote class="blockquote mb-0">
        <div class="media">
          <div class="media-avatar-wrap">
            <% if @pull_request.user.image? %>
              <%= image_tag(find_user.image_url) %>
            <% else %>
              <img src="https://images.plurk.com/43tXxZ1MP3bwW7lyZbunAy.png">
            <% end %>
          </div>
          <div class="media-body">
            <div class="row">
              <div class="col-12">
                <div class="issue_description_inactive">
                  <%= to_markdown(@pull_request.description)%>
                </div>
                <%= form_for([:repository, @pull_request],remote: true) do |form|%>
                <div class= "issue_description_active">
                  <p><%= form.text_area :description ,type: "text_area", class:"area form-control" %></p>
                </div> 
                <h6><%= time_ago_in_words(@pull_request.created_at) %> ago</h6>
              </div>   
            </div>
          </div>
        </div>
      </blockquote>
      <div class="issue-comment-edit row">
        <div class="update-comment actions">            
          <%= form.button "Update-comment", id: "issue_description_update", class: "btn btn-secondary", type: "submit"%> 
          <% end %>
        </div>
      </div>
    
    </div>
  </div>



  <div class="timeline-group mt-5">
    <% @commits.each do |commit|%>
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <ul class="timeline list-group list-group-flush">
              <li>
                <div class="row list-item title">
                  <p><%= commit.committer.name %></p>
                  <p><%= time_ago_in_words(commit.date.utc) %> ago</p>
                </div>
                <div class="row list-item number">
                  <p><%= commit.message %></p>
                  <p><%= commit.sha[0..7] %></p>
                </div>
              </li>
            </ul>
          </div>
        </div>
      </div>
    <% end %>
  </div>

  <div class="commit-line"></div>
  <div class="merge_pr_place mt-4"></div> 

  <% @comments.each do |c| %>

    <div class="comment-info-container">
      <div class="card">
        <div class="card-header">
          <div class="row">
            <div class="issue-comment-name col-12">
              <h4><%= c.user.name %></h4>
              <div class="bottom-line"></div> 
            </div>       
            <div class="btn-group">
              <% if c.user == current_user %>
                <button type="button" class="btn btn-sm dropdown-toggle dropdown-toggle-split comment-more" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <span class="sr-only">Toggle Dropdown</span>
                </button>
                <div class="dropdown-menu">
                  <div><%= link_to "Delete",  repository_pull_request_comment_path(user_name: c.user.name, repository_id: current_repository.title , pull_request_id: @pull_request, id: c), class: "btn comment-delete-button", data: {method: "DELETE", confirm: "Are you sure you want to delete?"} %></div>
                  <div class="btn comment-edit-button">Edit</div>
                </div>
              <% end %>       
            </div>
          </div>      
        </div>
        
        <div class="card-body">
          <blockquote class="blockquote mb-0">
            <div class="media">
              <div class="media-avatar-wrap">
                <% if @pull_request.user.image? %>
                  <%= image_tag(find_user.image_url) %>
                <% else %>
                  <img src="https://images.plurk.com/43tXxZ1MP3bwW7lyZbunAy.png">
                <% end %>
              </div>
              <div class="media-body">
                <p><%= to_markdown(c.content)%></p>
                <h6><%= time_ago_in_words(c.created_at) %>ago</h6>
              </div>
            </div>
          </blockquote>
        </div>
          
      </div>
    </div>


    <div class="comment-edit-container" style="display: none;">
      <%= form_with(model: c, url: repository_pull_request_comment_path(user_name: c.user.name, repository_id: current_repository.title , pull_request_id: @pull_request, id: c), method: "PUT") do |f| %>

        <% if c.errors.any? %>
          <ul>
            <% c.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        <% end %>

        <div class="comment-info-container">
          <div class="card">
            <div class="card-header">
              <div class="row">
                <div class="issue-comment-name col-12">
                  <h4><%= c.user.name %></h4>
                  <div class="bottom-line"></div> 
                </div>       
              </div>

            </div>
            <div class="card-body">
              <blockquote class="blockquote mb-0">
                <div class="media">
                  <div class="media-avatar-wrap">
                    <% if @pull_request.user.image? %>
                      <%= image_tag(find_user.image_url) %>
                    <% else %>
                      <img src="https://images.plurk.com/43tXxZ1MP3bwW7lyZbunAy.png">
                    <% end %>
                  </div>
                  <div class="media-body">
                    <h6>
                      <%= f.text_area :content, class: "area form-control"%>
                    </h6>
                    <h6><%= time_ago_in_words(c.created_at) %> ago </h6>
                  </div>
                </div>
              </blockquote>
              <div class="issue-comment-edit row">
                <div class="update-comment actions">            
                  <%= f.submit "Update comment", class: "btn btn-success" %>
                </div>
                <div class="btn btn-danger comment-cancel-button">
                  Cancel
                </div>
                </div>
              </div>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
      
  <div class="comment-new-container">
    <%= form_with(model: @comment, url: repository_pull_request_comments_path(pull_request_id: @pull_request), local: true, method: "POST") do |f|%>

      <% if @comment.errors.any? %>
        <ul>
          <% @comment.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      <% end %>
  
      <div class="actions text-area-container">
        <div class="form-group">

          <%= f.text_area :content, class: "area form-control"%>
          <% if find_user == current_user%>
            <div class="issue-comment-btn row">
              <div class="status-container mr-2">
                <% if @pull_request.status == 'Open' && @have_conflicts == false %>
                  <div id="merge_pr_btn">
                    <%= link_to 'Merge pull request', merge_repository_pull_request_path(user_name: find_user.name, repository_id: current_repository.title, id: @pull_request), class: 'btn merge-btn', method: 'POST' %>
                  </div>
                  <%= link_to "Close pull request", close_repository_pull_request_path(user_name: find_user.name, repository_id: current_repository.title, id: @pull_request), class: 'btn close-btn', method: 'POST'%>
                <% elsif @pull_request.status == 'Open' && @have_conflicts %>
                  <div class="conflict-info">
                    <p>There is conflict between two branches.</p> 
                    <p>Please resolve the conflict locally and try again.</p>
                    <p>You can try to <span>git checkout <%= @pull_request.compare_branch%></span> and do <span>git rebase <%= @pull_request.base_branch%></span> to resolve it.</p>
                      <p>If you finish rebasing, you can renew this pull request by <span>git push -f origin <%= @pull_request.compare_branch%></span>.
                    </p>
                  </div>
                  <%= link_to "Close pull request", close_repository_pull_request_path(user_name: find_user.name, repository_id: current_repository.title, id: @pull_request), class: 'btn close-btn', method: 'POST'%>
                <% elsif @pull_request.status == 'Merged' %>
                  <div class="merged-btn">
                    This pull request has been merged.
                  </div>
                <% else %>
                  <%= link_to "Reopen pull request", reopen_repository_pull_request_path(user_name: find_user.name, repository_id: current_repository.title, id: @pull_request), class: 'btn reopen-btn', method: 'POST'%>
                <% end %>
              </div>
            <% end %>
            <%= f.submit "Create comment", class: "comment-submit btn btn-success" %>         
          </div>
        </div>
      </div>
    <% end %>

  </div>
</div>

app/views/pull_requests/update.js.erb
$('.issue_name_inactive h1').text("<%= @pull_request.name %>")
$('.issue_description_inactive').text("<%= escape_javascript @pull_request.description %>")