config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
                        registrations: 'users/registrations',
                        omniauth_callbacks: "users/omniauth_callbacks"
                     }, 
                     path_names: { 
                        sessions: "sessions", 
                        sign_up: 'register', 
                        sign_in: 'login', 
                        sign_out: 'logout'
                     }

  root "home#index" 
  resources :home , only: [:index] do
    collection do 
      get :verification
    end
  end
  get ':user_name', to: "home#logged_in", as: "logged_in"
  resources :sshkeys, only:[:new, :create, :destroy]

  scope '/:user_name' do
    resources :relationships, only: [:index, :create, :destroy]
    get "relationships/followers", to: "relationships#followers", as: "followers"
    resources :likes, only: [:index]
    get "repository/:id/branches", to: "repositories#branches", as: "branches"
    post "repository/:id/branches/delete", to: "repositories#branch_delete", as: "branch_delete"
    get "repository/:id/commits", to: "repositories#commits", as: "commits"
    post "repository/:id/checkout", to: "repositories#checkout", as: "checkout"
    get "repository/:id/commit/diff", to: "repositories#commit_diff", as: "commit_diff"
    resources :repositories do
      resources :likes, only: [:create, :destroy]
      resources :pull_requests do
        member do
          get "commits", to: "pull_requests#commits", as: "commits"
          get "files_changed", to: "pull_requests#files_changed", as: "files_changed"
        end
        resources :comments, only:[:create, :update, :destroy]
        collection do
          get :compare
          get :diff
          get :close_index
        end
        member do
          post :merge
          post :close
          post :reopen
        end
      end
      resources :issues do
        resources :comments, only:[:create, :update, :destroy]
        member do
          get :toggle_status      
        end
      end
    end
  end
  get "/:user_name/repositories/:id/worktree/master/*file", to: "repositories#show" 

end

app/views/shared/_footer.html.erb
<div class="foot">
  <div class="logo_name">
	  <div class="logo"></div>
	  <p>© 2020 FengChenShowGit, 5xHermione</p>
  </div>
</div>

app/views/shared/_homepage.html.erb
<div class="thisIsUsresIndex">
  <div class="container my-5">
    <div class="row">
      <div class="user-info-container col-12 col-md-3">
        <div class="avatar-wrap">
          <img class="w-100" src="https://picsum.photos/400/400?random=1" alt="">
        </div>
        <h4 class="my-2">NAME：<%= current_user.name%></h4>
        <h4 class="my-2">ID：<%= current_user.id%></h4>
      </div>
      <div class="repositories-container col-12 col-md-9 row p-3">
        <div class="repositories-title col-12">
          <ul class="nav">
            <li class="nav-item">
              <%= link_to "Overview", root_path, class: "nav-link"%>
            </li>
            <li class="nav-item mx-3">
              <%= link_to "Repositories", repositories_path, class: "nav-link" %>
            </li>
          </ul>
        </div>
        <div class="title-bottom-line"></div>
        <h3 class="col-12 my-3">Popular repositories</h3>
        <% @repositories.each do |repo|%>
        <div class="p-3 col-6">
          <div class="overview-repository-wrap p-5">
            <h2>
              <%= link_to "#{repo.title}", repository_path(repo.id)%>
            </h2>
            <div>
              <%= repo.created_at%>
            </div>
          </div>
        </div>
        <% end %>
        <div class="green-wrap col-12">
          <div class="green_spots">
            <h2>這裡是留給綠點點的位置</h2>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="this-is-navbar">
  <nav class="navbar navbar-expand-lg navbar-light ">
    <%= link_to "", root_path, class: "navbar-brand"%>
    <button
      class="navbar-toggler collapsed"
      type="button"
      data-toggle="collapse"
      data-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <% if current_user%>
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <%= link_to "Home page", root_path, class: "nav-link"%> 
          </li>
          <li class="nav-item">
            <%= link_to "New repository", new_repository_path(current_user.name), class: "nav-link"%>
          </li>
            <li class="nav-item">
            <%= link_to "My repositories", repositories_path(current_user.name), class: "nav-link"%>
          </li>
        </ul>
        <ul class="ul-inline my-2 my-lg-0 ">
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <div class="avatarsmall">
                <% if current_user.image? %>
                    <%= image_tag(current_user.image_url) %>
                <% else %>
                    <img src="https://images.plurk.com/43tXxZ1MP3bwW7lyZbunAy.png">
                <% end %>
              </div>
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <%= link_to "User Settings", edit_user_registration_path, class: "dropdown-item user_set"%>
              <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "dropdown-item user_set"%>
            </div>
          </li>
        </ul>
      <% else %>
        <ul class="navbar-nav mr-auto">
          <li class="nav-item sp">
            <%= link_to "Sign up", new_user_registration_path, class: "nav-link"%>
          </li>
          <li class="nav-item">
            <%= link_to "Sign in", new_user_session_path, class: "nav-link"%>
          </li>
        </ul>
      <% end %>   
    </div>
  </nav>
</div> 

app/views/shared/_pull_request_bar.html.erb
<ul class="nav my-3 pr-nav-bar">
  <li class="nav-item m-auto">
    <%= link_to "Conversation", repository_pull_request_path(user_name: find_user.name, repository_id: current_repository.title, id: @pull_request)%>
  </li>
  <li class="nav-item m-auto">
    <%= link_to "Commits", commits_repository_pull_request_path(user_name: find_user.name, repository_id: current_repository.title, id: @pull_request) %>
  </li>
  <li class="nav-item m-auto">
    <%= link_to "Files changed", files_changed_repository_pull_request_path(user_name: find_user.name, repository_id: current_repository.title, id: @pull_request) %>
  </li>
</ul>

app/views/shared/_repo_navbar.html.erb
<div class="repo-navbar public">
  
  <div class="id-name">
    <h2 class="userId"><%= find_user.name %></h2> 
    <h2 class="fileName"><%=  current_repository.title %></h2>
    <div class="repo-desc"><%= current_repository.description %></div>
  </div>

  <ul class="nav nav-tabs" id="myTab" role="tablist">

    <li class="nav-item">
      <%= link_to repository_path(id: current_repository), class: "nav-link bottomline" , ariaselected:"false" do %>
        <i class="fas fa-code"></i><span> Code</span>
      <% end %>
    </li>
    <li class="nav-item">
      <%= link_to repository_issues_path(repository_id: current_repository), class: "nav-link" , ariaselected:"true" do %>
        <i class="fas fa-exclamation-circle"></i><span> Issues <%= current_repository.issues.count %></span>
      <% end %>
    </li>
    <li class="nav-item">
      <%= link_to repository_pull_requests_path(repository_id: current_repository), class: "nav-link" do %>
        <i class="fas fa-code-branch"></i><span> Pull requests <%= current_repository.pull_requests.where(status: "Open").count %></span>
      <% end %>
    </li>
    <% if current_user == find_user %>
      <li class="nav-item">
        <%= link_to edit_repository_path(id: current_repository), class: "nav-link" do %>
          <i class="fas fa-cog"></i><span> Setting</span>
        <% end %>
      </li>
    <% end%>
    <% if current_user.liked_repositories.find_by(id: current_repository.id).nil? %>
      <li class="nav-item ml-auto">
        <%= link_to repository_likes_path(repository_id: current_repository, is_show: true), class: "nav-link", method: "POST" do %>
          <i class="far fa-star"></i><span> <%= current_repository.likes.count %> Star </span>
        <% end %>
      </li>
    <% else %>
      <li class="nav-item ml-auto">
        <%= link_to repository_like_path(repository_id: current_repository.title, id: current_user.liked_repositories.find_by(id: current_repository.id)), class: "nav-link", method: "DELETE" do %>
          <i class="fas fa-star"></i><span>  <%= current_repository.likes.count %> Unstar </span>
        <% end %>
      </li>
    <% end %>
  </ul>
</div>