config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
                        registrations: 'users/registrations',
                        omniauth_callbacks: "users/omniauth_callbacks"
                     }, 
                     path_names: { 
                        sessions: "sessions", 
                        sign_up: 'register', 
                        sign_in: 'login', 
                        sign_out: 'logout'
                     }

  root "home#index" 
  resources :home , only: [:index] do
    collection do 
      get :verification
    end
  end
  get ':user_name', to: "home#logged_in", as: "logged_in"
  resources :sshkeys, only:[:new, :create, :destroy]

  scope '/:user_name' do
    resources :relationships, only: [:index, :create, :destroy]
    get "relationships/followers", to: "relationships#followers", as: "followers"
    resources :likes, only: [:index]
    get "repository/:id/branches", to: "repositories#branches", as: "branches"
    post "repository/:id/branches/delete", to: "repositories#branch_delete", as: "branch_delete"
    get "repository/:id/commits", to: "repositories#commits", as: "commits"
    post "repository/:id/checkout", to: "repositories#checkout", as: "checkout"
    get "repository/:id/commit/diff", to: "repositories#commit_diff", as: "commit_diff"
    resources :repositories do
      resources :likes, only: [:create, :destroy]
      resources :pull_requests do
        member do
          get "commits", to: "pull_requests#commits", as: "commits"
          get "files_changed", to: "pull_requests#files_changed", as: "files_changed"
        end
        resources :comments, only:[:create, :update, :destroy]
        collection do
          get :compare
          get :diff
          get :close_index
        end
        member do
          post :merge
          post :close
          post :reopen
        end
      end
      resources :issues do
        resources :comments, only:[:create, :update, :destroy]
        member do
          get :toggle_status      
        end
      end
    end
  end
  get "/:user_name/repositories/:id/worktree/master/*file", to: "repositories#show" 

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  helper_method :resource_name, :resource, :devise_mapping, :resource_class
  
  def index
    if user_signed_in?
      @repositories = current_user.repositories.order("id DESC")
      @users = User.all.order("RANDOM()").limit(5)

      redirect_to logged_in_path(current_user.name)
    end
  end

  def verification
    @verification = User.where(name: params[:name]).or(User.where(email: params[:email])).exists?
    respond_to do |format|
      format.json { render json: !@verification }
    end 
  end

  def logged_in
    if user_signed_in?
      if current_user == find_user
        @repositories = repositories_order
      else
        @repositories = repositories_order.select{ |repo| repo.is_public == true }
      end
      @users = User.where("id != ?", current_user.id).order("RANDOM()").limit(10)
    else
      redirect_to root_path, notice: 'Please login first.'
    end
  end

  # 這四方法來自 devise ，使用在首頁的註冊及登入表單
  def resource_class
    devise_mapping.to
  end

  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/views/home/index.html.erb
<div class="container-field unlogin homepage">
  <div class="container">
    <div class="row">
      <div class="logo-container col-12 col-md-6 m-auto">
        <img class="index_logo" src="https://images.plurk.com/isj6SfXFY8z5fw31EnnMx.png" alt="">
        <h1>FengChenShowGit</h1>
        <h2>Built for developers XD</h2>
        <p>FengChenShowGit is a development platform inspired by the way you work. From open source to business, you can host and review code, manage projects, and build software alongside 50 million developers.</p>
      </div>
      <div class="p-5 col-12 col-md-6">
        <div class="card bg-light">
        <h4 class="card-header">Sign Up</h4>
        <div class="card-body">
          <div>
            <%= render 'devise/shared/new'%>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/home/logged_in.html.erb
<div class="user-index public">
  
      <div class="container my-5">
        <div class="row">
          <div class="user-info-container col-12 col-md-3">
            <div class="avatar-wrap">
              <% if find_user.image? %>
                  <%= image_tag(find_user.image_url) %>
              <% else %>
                  <img src="https://images.plurk.com/43tXxZ1MP3bwW7lyZbunAy.png">
              <% end %>
            </div>
            <h4 class="my-2 user-name"><%= find_user.name%></h4>
          </div>
          <div class="repositories-container col-12 col-md-9 row p-3">
            <div class="repositories-title col-12">
              <ul class="nav">
                <li class="nav-item mx-3">
                  <%= link_to "Overview", logged_in_path(user_name: find_user.name), class: "nav-link the-bottom"%>
                </li>
                <li class="nav-item mx-3">
                  <%= link_to "Repositories #{find_user.repositories.count}", repositories_path, class: "nav-link" %>
                </li>
                <li class="nav-item mx-3">
                  <%= link_to "Following #{find_user.following_users.count}", relationships_path(user_name: find_user.name), class: "nav-link" %>
                </li>
                <li class="nav-item mx-3">
                  <%= link_to "Followers #{find_user.followers.count}", followers_path(user_name: find_user.name), class: "nav-link" %>
                <li class="nav-item mx-3">
                  <%= link_to "Stars #{find_user.liked_repositories.count}", likes_path(user_name: find_user.name), class: "nav-link" %>
                </li>
              </ul>
              <div class="line">
                <div class="title-bottom-line"></div>
              </div>
            </div>

            <% @repositories.each do |repo|%>
              <div class="p-3 col-12">
                <div class="overview-repository-wrap p-5 project-block">
                  <h4>
                    <%= link_to "#{repo.title}", repository_path(id: repo)%>
                  </h4>
                  <div>
                    Create <%= time_ago_in_words(repo.created_at) %> ago
                  </div>
                </div>
              </div>
            <% end %>
          <div class="green-wrap col-12">
            
          </div>
          <h2 class="col-12 popu other-users">Other users</h2>
            <% @users.each do |user| %>
              <div id= "follower-block" class="col-12 other-user-wrap project-block ">
                <div class="other-user-information">
                  <div class="other-user-avatar">
                    <% if user.image_url.nil?%>
                        <img src="https://images.plurk.com/43tXxZ1MP3bwW7lyZbunAy.png">
                    <% else %>
                        <%= image_tag(user.image_url) %>
                    <% end %>
                  </div>
                  <div class="information">
                      <p>
                        <%= link_to "#{user.name}", logged_in_path(user_name: user.name)%>
                      </p>
                      <% if user.passive_relationships.select{|follower| current_user.active_relationships.include?(follower)}.blank?  %>
                        <p class="follow sbtn">
                          <i class="far fa-star"></i>
                          <%= link_to " Follow", relationships_path(user_name: user.name), method: "POST"%>
                        </p>
                      <% else %>
                        <p class="follow sbtn">
                          <i class="fas fa-star"></i>
                          <%= link_to "Unfollow", relationship_path(user_name: user.name, id: user.passive_relationships.select{|follower| current_user.active_relationships.include?(follower)}.first.id), method: "DELETE" %>
                        </p>
                      <% end %>
                  </div>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>
</div>

app/views/home/logined.html.erb
  <div class="thisIsUsresIndex">
      <div class="container my-5">
        <div class="row">
          <div class="user-info-container col-12 col-md-3">
            <div class="avatar-wrap">
              <img class="w-100" src="https://picsum.photos/400/400?random=1" alt="">
            </div>
            <h4 class="my-2">NAME：<%= current_user.name%></h4>
            <h4 class="my-2">ID：<%= current_user.id%></h4>
          </div>
          <div class="repositories-container col-12 col-md-9 row p-3">
            <div class="repositories-title col-12">
              <ul class="nav">
                <li class="nav-item">
                  <%= link_to "Overview", root_path, class: "nav-link"%>
                </li>
                <li class="nav-item mx-3">
                  <%= link_to "Repositories", repositories_path, class: "nav-link" %>
                </li>
              </ul>
            </div>
            <div class="title-bottom-line"></div>
            <h3 class="col-12 my-3">Popular repositories</h3>
            <% @repositories.each do |repo|%>
              <div class="p-3 col-6">
                <div class="overview-repository-wrap p-5">
                  <h2>
                    <%= link_to "#{repo.title}", repository_path(id: repo)%>
                  </h2>
                  <div>
                    <%= repo.created_at%>
                  </div>
                </div>
              </div>
            <% end %>
          <div class="green-wrap col-12">

            <div class="green_spots">
              <h2>這裡是留給綠點點的位置</h2>
            </div>
            
          </div>
          </div>
        </div>
      </div>


  </div>